### ISSUE TITLE
Request Method

### ISSUE THREAD

**Issue by johnson-abraham** [HarishmaA/ServletExamples#1]
Why POST?

https://github.com/HarishmaA/ServletExamples/blob/a89688e9d682e594f01018656a2cccfda2158f18/Calculator/src/main/webapp/index.html#L9

**Comment by HarishmaA** [comment]
I thought I am sending data to the server so I used POST method. But those data are not sensitive so GET can be used. I will change it. Thanks for the comment and sorry for late reply.
